title: Github Pages Without Git
email: peter.binkley@ualberta.ca
description: >- # this means to ignore newlines until "baseurl:"
  A proof of concept
baseurl: "/github-pages-without-git" # the subpath of your site, e.g. /blog
url: "https://pbinkley.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pabinkley
github_username:  pbinkley

theme: jekyll-theme-slate
